services:
  traefik:
    image: traefik:v3
    volumes:
      - ./traefik.yml:/traefik.yml:ro
      - ./acme.json:/letsencrypt/acme.json
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports: ["80:80", "443:443"]
    networks: ["traefik-public"]
    restart: unless-stopped

networks:
  traefik-public:
    name: traefik-public
    external: true
