services:
  traefik:
    image: traefik:v3
    environment:
      # # On laisse le proxy actif pour l'ext√©rieur si besoin :
      # - HTTP_PROXY=http://192.168.6.52:8080
      # - http_proxy=http://192.168.6.52:8080
      # - HTTPS_PROXY=http://192.168.6.52:8080
      # - https_proxy=http://192.168.6.52:8080

      # Mais on exclut les IP Docker et localhost
      - NO_PROXY=127.0.0.1,localhost,172.16.0.0/12
      - no_proxy=127.0.0.1,localhost,172.16.0.0/12
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/ssl/certs/_.copelia.fr.crt:/certs/_.copelia.fr.crt:ro
      - /etc/ssl/keys/copelia.fr_private.key:/certs/copelia.fr_private.key:ro
      - ./dynamic:/etc/traefik/dynamic:ro
    ports: ["80:80", "443:443"]
    networks: ["traefik-public"]
    restart: unless-stopped

networks:
  traefik-public:
    name: traefik-public
    external: true
