services:
  traefik:
    image: traefik:v3
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/ssl/certs/_.copelia.fr.crt:/certs/_.copelia.fr.crt:ro
      - /etc/ssl/keys/copelia.fr_private.key:/certs/copelia.fr_private.key:ro
      - ./dynamic:/etc/traefik/dynamic:ro
    ports: ["80:80", "443:443"]
    networks: ["traefik-public"]
    restart: unless-stopped

networks:
  traefik-public:
    name: traefik-public
    external: true
