entryPoints:
  web:
    {
      address: ":80",
      http:
        { redirections: { entryPoint: { to: "websecure", scheme: "https" } } },
    }
  websecure: { address: ":443" }

providers:
  docker:
    network: traefik-public
    exposedByDefault: false

certificatesResolvers:
  le:
    acme:
      email: teintexpress@copelia.fr
      storage: /letsencrypt/acme.json
      httpChallenge: { entryPoint: web }
