entryPoints:
  web:
    {
      address: ":80",
      http:
        { redirections: { entryPoint: { to: "websecure", scheme: "https" } } },
    }
  websecure: { address: ":443", http: { tls: {} } }

providers:
  docker:
    network: traefik-public
    exposedByDefault: false
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

log:
  level: INFO
accessLog: {}
